autoload -z edit-command-line
zle -N edit-command-line

bindkey -v
bindkey -M vicmd "/" fzf-history-widget
bindkey -M vicmd v edit-command-line

SAVEHIST=8000
HISTFILE=~/.zsh_history

PROMPT='%(?.%F{green}⏺.%F{red}⏺)%f %2~ ❯ '

autoload -Uz add-zsh-hook vcs_info

setopt prompt_subst
setopt share_history
setopt inc_append_history
setopt inc_append_history_time
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_save_no_dups
setopt hist_reduce_blanks

alias vz="fzf --bind 'enter:become(vim {})'"

export FZF_DEFAULT_COMMAND='ag -l "."'
export FZF_DEFAULT_OPTS="-e \
	  --height 40% \
		--color dark \
		--layout=reverse"

alias ls='ls --color'
