autoload -z edit-command-line
zle -N edit-command-line

bindkey -v
bindkey -M vicmd "/" fzf-history-widget
bindkey -M vicmd v edit-command-line

PROMPT='%(?.%F{green}●.%F{red}●)%f %2~ ❯ '

autoload -Uz add-zsh-hook vcs_info
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

complete -C $(which aws_completer) aws

vz() {
	fzf -q "${*:-}" --bind 'enter:become(vim {})'
}
